steps:
  - name: gcr.io/cloud-builders/go
    env: ["PROJECT_ROOT=app"]
    args: ["build", "-o", "app"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/go-hello:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/go-hello:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    args:
      - clone
      - --recurse-submodules
      - git@github.com:kujilabo/kujilabo-manifests.git
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args:
      - checkout
      - master

  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args:
      - -c
      - |
        ls

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests/go-hello/overlays/develop"
    entrypoint: "bash"
    args:
      - -c
      - |
        ls

  - name: "gcr.io/$PROJECT_ID/kustomize"
    dir: "kujilabo-manifests/go-hello/overlays/develop"
    args:
      - "edit"
      - "set"
      - "image"
      - "gcr.io/cocotola/go-hello=gcr.io/$PROJECT_ID/go-hello:$SHORT_SHA"
    env:
      - "APPLY=false"
      - "CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=k8s-cluster"
      - "GCLOUD_PROJECT=cocotola"

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args:
      - add
      - .

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args:
      - commit
      - -m
      - "Update $SHORT_SHA"

  - name: "gcr.io/cloud-builders/git"
    dir: "kujilabo-manifests"
    args:
      - push
      - origin
      - master
    volumes:
      - name: "ssh"
        path: /root/.ssh

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/go-hello-secret/versions/latest
      env: "SSH_KEY"

images:
  - "gcr.io/$PROJECT_ID/go-hello"
