steps:
  - name: gcr.io/cloud-builders/go
    env: ["PROJECT_ROOT=app"]
    args: ["build", "-o", "app"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/go-hello:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/go-hello:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/git"
    secretEnv: ["SSH_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  # Clone the repository
  - name: "gcr.io/cloud-builders/git"
    args:
      - clone
      - --recurse-submodules
      - git@github.com:kujilabo/kujilabo-manifests.git
    volumes:
      - name: "ssh"
        path: /root/.ssh

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/go-hello-secret/versions/latest
      env: "SSH_KEY"

images:
  - "gcr.io/$PROJECT_ID/go-hello"
